services:
  internship-management-app-discovery-service:
    build: ./discovery-service
    container_name: internship-management-app-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4

  internship-management-app-config-service:
    build: ./config-service
    container_name: internship-management-app-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://internship-management-app-discovery-service:8761/eureka
    depends_on:
      internship-management-app-discovery-service:
          condition: service_healthy

  internship-management-app-supervisor-service:
    build: ./supervisor-service
    container_name: internship-management-app-supervisor-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://internship-management-app-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://internship-management-app-config-service:9999
    depends_on:
      internship-management-app-config-service:
        condition: service_healthy

  internship-management-app-internship-service:
    build: ./internship-service
    container_name: internship-management-app-internship-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://internship-management-app-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://internship-management-app-config-service:9999
    depends_on:
      internship-management-app-supervisor-service:
        condition: service_healthy
